In [4]:
import sys
import os
os.getcwd()

'C:\\Users\\persp\\workspace\\GitHub\\Hands-on-Machine-Learning'

In [12]:
import jieba.posseg as pseg
import synonyms

var = synonyms.nearby('人脸')
print(var)
type (var)
var[0]
var[1]
var[]

(['人脸', '图片', '通过观察', '几何图形', '图象', '放大镜', '面孔', '貌似', '奇特', '十分相似'], [1.0, 0.5972838, 0.56848586, 0.53183466, 0.5253439, 0.52400935, 0.52310055, 0.5006411, 0.4851142, 0.39761642])


[1.0,
 0.5972838,
 0.56848586,
 0.53183466,
 0.5253439,
 0.52400935,
 0.52310055,
 0.5006411,
 0.4851142,
 0.39761642]

In [3]:
我是谁

NameError: name '我是谁' is not defined

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 
from sklearn.datasets import fetch_mldata
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

import numpy as np
mnist = fetch_mldata('MNIST original',data_home="C:/Users/persp/workspace/GitHub/Hands-on-Machine-Learning/datasets/")
mnist
X, y = mnist["data"], mnist["target"]
shuffle_index = np.random.permutation(len(X))
shuffle_index
X, y= X[shuffle_index], y[shuffle_index]
result =[]
# for sample_num in [1000,2000,4000,6000,8000,10000]:
for sample_num in [5000]:
#     for train_test_radio in [4,5,6]:
    for train_test_radio in [6]:

        x_sample,y_sample= X[:sample_num],y[:sample_num]
#         train_test_radio =5/1
        sample_train_num = int(sample_num*train_test_radio/(train_test_radio+1))
        x_sample_train,y_sample_train =x_sample[:sample_train_num],y_sample[:sample_train_num]
        x_sample_test,y_sample_test = x_sample[sample_train_num:],y_sample[sample_train_num:]
        # y_sample[0]==y_sample_train[0]
        # y_sample[-1]==y_sample_test[-1]


        knn_clf = KNeighborsClassifier()
        param_grid = [{'weights': [ "distance"], 'n_neighbors': [3, 4, 5]}]
        # 网格搜索
        grid_search = GridSearchCV(knn_clf, param_grid, cv=3, verbose=3, n_jobs=-1)
        grid_search.fit(x_sample_train, y_sample_train)
        print('sample_num,train_test_radio')
        print((sample_num,train_test_radio))
        print(('best_score' + str(grid_search.best_score_)))

        y_sample_pred = grid_search.predict(x_sample_test)
        test_score =accuracy_score(y_sample_test, y_sample_pred)
        result.append([sample_num,train_test_radio,grid_search.best_params_,test_score])
result

C:\Users\persp\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\persp\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)


Fitting 3 folds for each of 3 candidates, totalling 9 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 
from sklearn.datasets import fetch_mldata
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

import numpy as np
mnist = fetch_mldata('MNIST original',data_home="C:/Users/persp/workspace/GitHub/Hands-on-Machine-Learning/datasets/")
mnist
X, y = mnist["data"], mnist["target"]
shuffle_index = np.random.permutation(len(X))
shuffle_index
X, y= X[shuffle_index], y[shuffle_index]


sample_num =1000
train_test_radio =6
x_sample,y_sample= X[:sample_num],y[:sample_num]
sample_train_num = int(sample_num*train_test_radio/(train_test_radio+1))
x_sample_train,y_sample_train =x_sample[:sample_train_num],y_sample[:sample_train_num]
x_sample_test,y_sample_test = x_sample[sample_train_num:],y_sample[sample_train_num:]

knn_clf = KNeighborsClassifier(n_jobs=-1, weights='distance', n_neighbors=4)
knn_clf.fit(x_sample_train, y_sample_train)
y_sample_pred = knn_clf.predict(x_sample_test)
accuracy_score(y_sample_test, y_sample_pred)
## Data Augmentation

##
print('shift')
from scipy.ndimage.interpolation import shift
def shift_image(image, dx, dy):
    image = image.reshape((28, 28))
    shifted_image = shift(image, [dy, dx], cval=0, mode="constant")
    return shifted_image.reshape([-1])
print('shape')
x_sample_train.shape
X_train_augmented = [image for image in x_sample_train]
y_train_augmented = [label for label in y_sample_train]

for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
    for image, label in zip(x_sample_train, y_sample_train):
        X_train_augmented.append(shift_image(image, dx, dy))
        y_train_augmented.append(label)

X_train_augmented = np.array(X_train_augmented)
y_train_augmented = np.array(y_train_augmented)


shuffle_idx = np.random.permutation(len(X_train_augmented))
X_train_augmented = X_train_augmented[shuffle_idx]
y_train_augmented = y_train_augmented[shuffle_idx]
knn_clf = KNeighborsClassifier(**grid_search.best_params_)
knn_clf.fit(X_train_augmented, y_train_augmented)
y_sample_pred = knn_clf.predict(x_sample_test)
accuracy_score(y_sample_test, y_sample_pred)

C:\Users\persp\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\persp\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)


{'COL_NAMES': ['label', 'data'],
 'DESCR': 'mldata.org dataset: mnist-original',
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'target': array([0., 0., 0., ..., 9., 9., 9.])}

array([22391, 38477, 43348, ..., 40739, 60559, 42356])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=4, p=2,
           weights='distance')

0.8881118881118881

shift
shape


(857, 784)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=4, p=2,
           weights='distance')

0.9090909090909091

In [4]:
len(X_train_augmented)

4285

In [12]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.c_[a,b]

print((np.r_[a,b]))
print('')
print(c)
print('')
print((np.c_[c,a]))

[1 2 3 4 5 6]

[[1 4]
 [2 5]
 [3 6]]

[[1 4 1]
 [2 5 2]
 [3 6 3]]


In [1]:
import numpy as np
from sklearn.datasets import fetch_california_housing

reset_graph()

housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

NameError: name 'reset_graph' is not defined